title:            Dora Hu
description:      A jekyll theme. Because I scribble.
url:              www.dorahu.com
signoff:          Dora Hu
disqus_shortname: # disqus comment thread for post header options. ( leave blank if unwanted. )
facebook_appid:   # appid for like button, remove from /_includes/share.html if unwanted.
google_analytics: # set tracking, remove from /javascripts/basic.js if unwanted.

links:
  - name:         Home
    url:          /
  - name:     Services
    url:          /services
  - name:         About
    url:          /about
    external:     true
  - name:         contact
    url:          /contact
  - name:         Chinese
    url:          /chinese
highlighter:      pygments
permalink:        pretty
markdown:         redcarpet
redcarpet:
  extensions:
    - smart
